name: Pipeline
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: app_db
          POSTGRES_PASSWORD: app_password
          POSTGRES_USER: app_user
        ports:
          - 5432:5432

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v4

      - name: instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      
      - name: Instalar dependeicas do projeto
        run: pip install -r requirements.txt

      - name: rodar os tests 
        run: pytest -v 